# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tasarim.ui'
#
# Created: Sat Dec 30 17:42:14 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(753, 576)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 711, 561))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 281, 201))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.txt_x = QtGui.QLineEdit(self.groupBox)
        self.txt_x.setGeometry(QtCore.QRect(110, 30, 113, 20))
        self.txt_x.setObjectName(_fromUtf8("txt_x"))
        self.txt_y = QtGui.QLineEdit(self.groupBox)
        self.txt_y.setGeometry(QtCore.QRect(110, 60, 113, 20))
        self.txt_y.setObjectName(_fromUtf8("txt_y"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 101, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 101, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lbl_bilgi = QtGui.QLabel(self.groupBox)
        self.lbl_bilgi.setGeometry(QtCore.QRect(20, 170, 46, 13))
        self.lbl_bilgi.setObjectName(_fromUtf8("lbl_bilgi"))
        self.btn_knn_siniflandir = QtGui.QPushButton(self.groupBox)
        self.btn_knn_siniflandir.setGeometry(QtCore.QRect(140, 130, 91, 31))
        self.btn_knn_siniflandir.setObjectName(_fromUtf8("btn_knn_siniflandir"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 101, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.txt_k = QtGui.QLineEdit(self.groupBox)
        self.txt_k.setGeometry(QtCore.QRect(110, 90, 113, 20))
        self.txt_k.setObjectName(_fromUtf8("txt_k"))
        self.btn_knn_goster = QtGui.QPushButton(self.groupBox)
        self.btn_knn_goster.setGeometry(QtCore.QRect(40, 130, 91, 31))
        self.btn_knn_goster.setObjectName(_fromUtf8("btn_knn_goster"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 220, 281, 171))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 101, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 101, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.txt_x2 = QtGui.QLineEdit(self.groupBox_2)
        self.txt_x2.setGeometry(QtCore.QRect(110, 30, 113, 20))
        self.txt_x2.setObjectName(_fromUtf8("txt_x2"))
        self.txt_y_2 = QtGui.QLineEdit(self.groupBox_2)
        self.txt_y_2.setGeometry(QtCore.QRect(110, 60, 113, 20))
        self.txt_y_2.setObjectName(_fromUtf8("txt_y_2"))
        self.combo_kmeans = QtGui.QComboBox(self.groupBox_2)
        self.combo_kmeans.setGeometry(QtCore.QRect(110, 90, 101, 22))
        self.combo_kmeans.setObjectName(_fromUtf8("combo_kmeans"))
        self.combo_kmeans.addItem(_fromUtf8(""))
        self.combo_kmeans.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 90, 81, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.btn_kmeans_goster = QtGui.QPushButton(self.groupBox_2)
        self.btn_kmeans_goster.setGeometry(QtCore.QRect(30, 120, 75, 31))
        self.btn_kmeans_goster.setObjectName(_fromUtf8("btn_kmeans_goster"))
        self.btn_kmeans_kumele = QtGui.QPushButton(self.groupBox_2)
        self.btn_kmeans_kumele.setGeometry(QtCore.QRect(120, 120, 75, 31))
        self.btn_kmeans_kumele.setObjectName(_fromUtf8("btn_kmeans_kumele"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 400, 281, 131))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.btn_knn_kume1 = QtGui.QPushButton(self.groupBox_3)
        self.btn_knn_kume1.setGeometry(QtCore.QRect(50, 20, 141, 41))
        self.btn_knn_kume1.setObjectName(_fromUtf8("btn_knn_kume1"))
        self.radio_oklid = QtGui.QRadioButton(self.groupBox_3)
        self.radio_oklid.setGeometry(QtCore.QRect(20, 80, 82, 17))
        self.radio_oklid.setObjectName(_fromUtf8("radio_oklid"))
        self.radio_minkowski = QtGui.QRadioButton(self.groupBox_3)
        self.radio_minkowski.setGeometry(QtCore.QRect(70, 80, 82, 17))
        self.radio_minkowski.setObjectName(_fromUtf8("radio_minkowski"))
        self.radio_manhattan = QtGui.QRadioButton(self.groupBox_3)
        self.radio_manhattan.setGeometry(QtCore.QRect(150, 80, 82, 17))
        self.radio_manhattan.setObjectName(_fromUtf8("radio_manhattan"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(320, 0, 311, 251))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.resim_goster = QtGui.QGraphicsView(self.groupBox_4)
        self.resim_goster.setGeometry(QtCore.QRect(10, 20, 291, 211))
        self.resim_goster.setObjectName(_fromUtf8("resim_goster"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(320, 260, 321, 241))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.resim_goster2 = QtGui.QGraphicsView(self.groupBox_5)
        self.resim_goster2.setGeometry(QtCore.QRect(10, 20, 291, 211))
        self.resim_goster2.setObjectName(_fromUtf8("resim_goster2"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 10, 661, 201))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.txt_metin = QtGui.QLineEdit(self.groupBox_6)
        self.txt_metin.setGeometry(QtCore.QRect(10, 40, 341, 141))
        self.txt_metin.setObjectName(_fromUtf8("txt_metin"))
        self.btn_naive = QtGui.QPushButton(self.groupBox_6)
        self.btn_naive.setGeometry(QtCore.QRect(400, 60, 161, 51))
        self.btn_naive.setObjectName(_fromUtf8("btn_naive"))
        self.label_7 = QtGui.QLabel(self.groupBox_6)
        self.label_7.setGeometry(QtCore.QRect(30, 20, 101, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_6)
        self.label_8.setGeometry(QtCore.QRect(385, 140, 41, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lbl_naive = QtGui.QLabel(self.groupBox_6)
        self.lbl_naive.setGeometry(QtCore.QRect(430, 140, 171, 16))
        self.lbl_naive.setText(_fromUtf8(""))
        self.lbl_naive.setObjectName(_fromUtf8("lbl_naive"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.groupBox.setTitle(_translate("Form", "Knn Sınıflandırma", None))
        self.label.setText(_translate("Form", "X koordiantını giriniz:", None))
        self.label_2.setText(_translate("Form", "Y koordiantını giriniz:", None))
        self.lbl_bilgi.setText(_translate("Form", "Bilgi", None))
        self.btn_knn_siniflandir.setText(_translate("Form", "Sınıflandır", None))
        self.label_3.setText(_translate("Form", "K degerini giriniz:", None))
        self.btn_knn_goster.setText(_translate("Form", "Göster", None))
        self.groupBox_2.setTitle(_translate("Form", "K-Means Kümeleme", None))
        self.label_4.setText(_translate("Form", "X koordiantını giriniz:", None))
        self.label_5.setText(_translate("Form", "X koordiantını giriniz:", None))
        self.combo_kmeans.setItemText(0, _translate("Form", "c1", None))
        self.combo_kmeans.setItemText(1, _translate("Form", "c2", None))
        self.label_6.setText(_translate("Form", "Etiketini Seçiniz:", None))
        self.btn_kmeans_goster.setText(_translate("Form", "Göster", None))
        self.btn_kmeans_kumele.setText(_translate("Form", "Kümele", None))
        self.groupBox_3.setTitle(_translate("Form", "Knn Kümeleme", None))
        self.btn_knn_kume1.setText(_translate("Form", "Rastgele Data Oluştur", None))
        self.radio_oklid.setText(_translate("Form", "Ökid", None))
        self.radio_minkowski.setText(_translate("Form", "Minkowski", None))
        self.radio_manhattan.setText(_translate("Form", "Manhattan", None))
        self.groupBox_4.setTitle(_translate("Form", "İşlem Öncesi", None))
        self.groupBox_5.setTitle(_translate("Form", "İşlem Sonrası", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Knn/Kmeans", None))
        self.groupBox_6.setTitle(_translate("Form", "Naive Bayes ", None))
        self.btn_naive.setText(_translate("Form", "Kategorisini Bul", None))
        self.label_7.setText(_translate("Form", "Metin Giriniz", None))
        self.label_8.setText(_translate("Form", "Sonuç", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Naive Bayes", None))

